const val STR_WELCOME_MESSAGE = "숫자 야구 게임을 시작합니다."
const val STR_INPUT_MESSAGE = "숫자를 입력해주세요 : "
const val STR_BALL = "볼"
const val STR_STRIKE = "스트라이크"
const val STR_NOTHING = "낫싱"
const val STR_GAME_END = "3개의 숫자를 모두 맞히셨습니다! 게임 종료"
const val STR_ASK_RESTART_MESSAGE = "게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요."